# connect via
# psql -h 192.168.99.100 --port 54678 -U postgres my_database
  #image: "postgres:13.5"

version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    container_name: "r7stripe_postgres"
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: "merlin123"
    ports:
      - 54678:5432
    volumes:
      - r7stripe_dbdata:/var/lib/postgresql/data
  redis:
    image: redis:7.0.8
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 16969
        protocol: tcp
        mode: host
    volumes:
        - r7stripe_redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  r7stripe_redis_data:
  r7stripe_dbdata: